### ISSUE TITLE
Bug: Support newer uuid version

### ISSUE THREAD

**Issue by c-seeger** [Floating-Dartists/matomo-tracker#140]
**Describe the bug**
the current tagged version does not support newer uuid version. The commit that changed this is from January 30 but the last release was October 12 last year. Please create a new release tag to get this change into the latest version.

**To Reproduce**
add uuid >=4.1.0 
then try to add matomo_tracker

**Expected behavior**
works

**Comment by c-seeger** [comment]
cc: @TesteurManiak

**Comment by c-seeger** [comment]
Quick workaround for now (since the fix is in main but not in any tag):

pubspec.yaml
```
matomo_tracker:
  git:
    url: git@github.com:Floating-Dartists/matomo-tracker.git
    ref: main

```

**Comment by TesteurManiak** [comment]
Closing this as solved by #136

**Comment by c-seeger** [comment]
this doesn't solve the issue since the fix is not released yet

**Comment by TesteurManiak** [comment]
It does, the fact that it is not on pub.dev doesn't mean that the issue is not fixed. The PR has been merged and I've already explained in [this comment](https://github.com/Floating-Dartists/matomo-tracker/pull/138#issuecomment-1954601752) why we haven't already published a new release. Keeping this issue open is not needed.

**Comment by c-seeger** [comment]
I see. Makes sense. The part you mentioned in the comment was the missing piece here. :+1:
